name: autoawq
channels:
  - pytorch
  - nvidia
  - defaults
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - python=3.10
  - pip
  - numpy
  - filelock
  - mkl
  - mkl-service
  - mkl_fft
  - mkl_random
  - networkx
  - gmpy2
  - freetype
  - lcms2
  - libpng
  - openjpeg
  - lz4-c
  - zlib
  - xz
  - zstd
  - tk
  - sqlite
  - ca-certificates
  - certifi
  - openssl
  - ffmpeg
  - typing_extensions
  - readline
  - libffi
  - libuuid
  - libtiff
  - libdeflate
  - brotli-python
  - bzip2
  - libwebp-base
  - pip:
      - aiohappyeyeballs==2.6.1
      - aiohttp==3.11.18
      - aiosignal==1.3.2
      - async-timeout==5.0.1
      - attrs==25.3.0
      - av==14.3.0
      - datasets==3.5.0
      - decord==0.6.0
      - dill==0.3.8
      - einops==0.8.1
      - flash-attn==2.7.4.post1
      - frozenlist==1.6.0
      - fsspec==2024.6.1
      - huggingface-hub==0.30.2
      - multidict==6.4.3
      - multiprocess==0.70.16
      - nvidia-cublas-cu12==12.1.3.1
      - nvidia-cuda-cupti-cu12==12.1.105
      - nvidia-cuda-nvrtc-cu12==12.1.105
      - nvidia-cuda-runtime-cu12==12.1.105
      - nvidia-cudnn-cu12==9.1.0.70
      - nvidia-cufft-cu12==11.0.2.54
      - nvidia-curand-cu12==10.3.2.106
      - nvidia-cusolver-cu12==11.4.5.107
      - nvidia-cusparse-cu12==12.1.0.106
      - nvidia-nccl-cu12==2.21.5
      - nvidia-nvjitlink-cu12==12.1.105
      - nvidia-nvtx-cu12==12.1.105
      - packaging==25.0
      - pandas==2.2.3
      - pillow
      - propcache==0.3.1
      - psutil==7.0.0
      - pyarrow==19.0.1
      - python-dateutil==2.9.0.post0
      - pytz==2025.2
      - PyYAML==6.0.2
      - qwen-vl-utils==0.0.8
      - regex==2024.11.6
      - requests
      - safetensors==0.5.3
      - six==1.17.0
      - sympy==1.13.1
      - tokenizers==0.21.1
      - tqdm==4.67.1
      - triton==3.1.0
      - tzdata==2025.2
      - urllib3
      - xxhash==3.5.0
      - yarl==1.20.0
      - zstandard==0.23.0
